name: uninstall
on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        mask-aws-account-id: true

    - name: Login Image Registry
      uses: aws-actions/amazon-ecr-login@v1

    - name: Delete API Gateway
      run: |
        awa apigateway delete-rest-api --rest-api-id stateful-serverless-api
        awa apigateway delete-usage-plan --usage-plan-id stateful-serverless-api
        awa apigateway delete-api-key --api-key stateful-serverless-api
      continue-on-error: true

    - name: Delete Functions
      run: aws lambda delete-function --function-name stateful-serverless-api
      continue-on-error: true

    - name: Delete Database Tables
      run: awa dynamodb delete-table --table-name stateful-serverless-api
      continue-on-error: true

    - name: Delete Image Repository
      run: awa ecr delete-repository --repository-name stateful-serverless-api --force
      continue-on-error: true

    - name: Delete Security Roles
      run: aws iam delete-role --role-name stateful-serverless-api
      continue-on-error: true
